version: "3"

services:
  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: phrases_janusgraph
    environment:
    - GREMLIN_REMOTE_HOSTS=janusgraph
    ports:
      - "8182:8182"
    # The mounted volume only makes sense if JanusGraph is being run with the BerekeleyDB storage.
    volumes:
      - "janusgraph-default-data:/var/lib/janusgraph"

volumes:
  janusgraph-default-data:
